### ISSUE TITLE
Missing host permission for the tab

### ISSUE THREAD

**Issue by ngirard** [diegodlh/unofficial-hypothesis-extension#9]
Hi,

I just installed and gave your extension a try. Unfortunately I'm getting the following error with all the pages I tested:

> Missing host permission for the tab

Any thoughts ?

Cheers

**Comment by ngirard** [comment]
I'm confused... I'm not getting the error any longer.
I don't know what happened.
Closing for now. Will reopen if I can bring specific steps to reproduce.

Anyway, thanks for your work !
I noticed your fork is lagging behind the official extension, how about rebasing it ?

**Comment by diegodlh** [comment]
Hi, @ngirard! Thanks for your message.

> I noticed your fork is lagging behind the official extension, how about rebasing it ?

Yes, this has been chasing me for months, haha. Problem is last time I tried some months ago some changes made to the official client were in conflict with changes I'd made to the unofficial client, so rebasing implied some extra work.

Unfortunately, I haven't found the time lately to do it. I also have so many ideas I'd like to implement in the unofficial extension and client for which I haven't found the time either :(

I plan to do so as soon as I can. But if you or somebody else want to give it a try, cool!
